In [1]:
import poker
import numpy as np
from tqdm import tqdm

In [2]:
edges = []
for r in tqdm(range(1000000)):
    num_suits = 4
    num_ranks = 13
    
    deck = poker.Deck(num_suits, num_ranks)
    
    player_1 = poker.Player(200, np.mean)
    
    community = poker.CommunityCards()
    
    deck.deal_hole_cards([player_1], 2)
    deck.deal_flop(community)
    deck.deal_turn(community)
    deck.deal_river(community)
    
    hand_1 = player_1.hole_cards + community.cards

    edges.append(poker.hand_strength(hand_1)[0])

100%|██████████████████████████████| 1000000/1000000 [00:20<00:00, 49054.41it/s]


In [3]:
from collections import defaultdict
power = defaultdict(int)
for val in edges:
    power[val] += 1 / len(edges)

In [4]:
print(power[0])
print(power[1])
print(power[2])
print(power[3])
print(power[4])
print(power[5])
print(power[6])
print(power[7])
print(power[8])

0.17408000000015342
0.4386049999951831
0.23478200000021412
0.04864400000002799
0.04560000000002495
0.030418000000009767
0.0258520000000052
0.0017209999999999546
0.00029800000000000074


In [5]:
hand_1

In [6]:
hand_look = [(card.suit, card.rank) for card in hand_1]
print(hand_look)

[(0, 2), (0, 3), (3, 2), (2, 5), (2, 0), (3, 3), (3, 9)]


In [7]:
hand = hand_1[:3]

In [8]:
hand

In [9]:
for item in deck.deck:
    if item == hand[0]:
        print('found it')
        break

In [10]:
test = poker.simulate_outcomes(hand_1[:5])

In [11]:
print(test)

(array([1.77150786, 2.86493987, 2.82053654, 5.67160037, 4.50046253,
       5.50508788]), array([ 1.10422448,  2.91692706,  2.79924453, 18.61890568,  9.47060164,
        6.38909446]), array([7, 2, 2, 2, 2, 5]))


In [12]:
community.cards

In [13]:
other_test = poker.simulate_opposing_outcomes(player_1.hole_cards, community)

In [14]:
print(test[0])
print(test[1])
print(test[2])

[1.77150786 2.86493987 2.82053654 5.67160037 4.50046253 5.50508788]
[ 1.10422448  2.91692706  2.79924453 18.61890568  9.47060164  6.38909446]
[7 2 2 2 2 5]


In [15]:
print(other_test[0])
print(other_test[1])
print(other_test[2])

[1.02828283 7.07272727 6.25757576 7.11717172 4.94646465 3.53737374]
[ 1.62710625 14.79349205 10.71720746  8.11163608  4.78277313  3.3631114 ]
[ 5 12 11  9  3  2]


In [ ]:
community.cards

In [16]:
hand_look = [(card.suit, card.rank) for card in hand_1]
print(hand_look)

[(0, 2), (0, 3), (3, 2), (2, 5), (2, 0), (3, 3), (3, 9)]


In [11]:
test[0]

array([0.412843, 1.915243, 1.726321, 1.742104, 1.379233, 1.223763])

In [12]:
test[1]**(1/2)

array([1.13532152, 4.15948273, 3.75015158, 3.78049652, 3.08401635,
       2.90712531])

In [13]:
test[2]

array([ 8, 12, 11, 10,  9,  8])

In [ ]:
hand_1[:3]

In [123]:
hand_1[0].rank = 0
hand_1[1].rank = 1 
hand_1[2].rank = 10
hand_1[3].rank = 3
hand_1[4].rank = 13
hand_1[5].rank = 7


In [17]:
hand_look = [(card.suit, card.rank) for card in hand_1]
print(hand_look)

[(1, 8), (1, 0), (1, 12), (3, 12), (0, 4), (3, 4), (3, 3)]


In [125]:
poker.hand_strength(hand_1)

(4, 3, 2, 1, 0, 13)

In [28]:
import scipy as sp
sp.special.comb(45,3)

np.float64(14190.0)

In [29]:
sp.special.comb(45,3)

np.float64(14190.0)

In [31]:
int(sp.special.comb(45,3))

14190

In [19]:
import itertools
len(itertools.combinations(deck.deck, 3))

TypeError: object of type 'itertools.combinations' has no len()

In [68]:
player_4.hole_cards

[<poker.poker.Card at 0x105236fc0>, <poker.poker.Card at 0x1052705f0>]

In [69]:
community.cards

(1, 6, 6, 10, 8, 7)

In [51]:
hand_look = [(card.suit, card.rank) for card in hand_3]
print(hand_look)

[(0, 3), (0, 12), (0, 6), (2, 7), (3, 0), (2, 1), (3, 7)]


In [28]:
len(deck.deck)

45

In [29]:
import itertools
counter = 0
for comb in itertools.combinations(deck.deck, 3):
    counter += 1
print(counter)

14190
